### ISSUE TITLE
Cannot read 3mf files produced by Microsoft's 3D Builder

### ISSUE THREAD

**Issue by dalefugier** [3MFConsortium/lib3mf#1]
Hi Alexander,

I've been playing with your toolkit a little. I notice that the Converter.exe application, provided in the lib3mf-examples repository, cannot read (or convert) .3mf files produced by Microsoft's 3D Builder application. On any 3D Builder produced file, Converter.exe prints the following output:

'could not parse file: 80004005'

Debugging this in Rhino, I get the following:

'First-chance exception at 0x00007FFF7B738B9C in Rhino.exe: Microsoft C++ exception: NMR::CNMRException at memory location 0x00000043BB6F96B0.'

Let me know if you need more details.

Thanks,

-- Dale

**Comment by SimmonsTech** [comment]
Was there any update on this?

**Comment by alexanderoster** [comment]
Hi Stephen,

yes, there has been an update! The current trunk of the repository and the unstable version should support the 3D Builder 3MFs. 

Best,
 Alexander
