### ISSUE TITLE
sal.h on linux?

### ISSUE THREAD

**Issue by phaazon** [3MFConsortium/lib3mf#10]
Hi,

I’m compiling a program using the official lib3mf GCC build. When trying to import the file `<Common/Mesh/NMR_Mesh.h>`, I end up with an error:

```
g++ src/main.cpp -o stl-converter -std=c++11 -g -W -Wall -I/usr/local/include/lib3mf
In file included from /usr/local/include/lib3mf/Common/NMR_Local.h:39:0,
                 from /usr/local/include/lib3mf/Common/Math/NMR_Geometry.h:37,
                 from /usr/local/include/lib3mf/Common/Mesh/NMR_Mesh.h:44,
                 from src/main.cpp:2:
/usr/local/include/lib3mf/Common/Platform/NMR_SAL.h:39:17: fatal error: sal.h: No such file or directory
 #include <sal.h>
                 ^
compilation terminated.
Makefile:13: recipe for target 'obj' failed
make: *** [obj] Error 1
```

I tried to find a package to install that library or grab it to install it on my own but I can’t find it. Any ideas? Thanks guys.

**Comment by t-paul** [comment]
For me it works when using both the main include path and the Model/COM path and just including `NMR_DLLInterfaces.h` (and defining `__GCC`!). I'm not yet sure why this is needed as the examples seem to work with just the base path, but the examples use their own copy of the include files, so things might be different there.

```
-I/usr/local/include/lib3mf -I/usr/local/include/lib3mf/Model/COM -D__GCC
```

I did not find any existing packages either (Fedora already expressed interrest for packaging in #8, I'll try to check with our Debian maintainer if he's interested in packaging lib3mf for Debian). So in the meantime I've created some packages for use with OpenSCAD in https://build.opensuse.org/package/show/home:t-paul:lib3mf/lib3mf based on pull request #9. The other platforms supported by OBS and our nightly builds will follow... those are not meant as "production quality packaging" so details will probably change with "real" distro packaging.

**Comment by phaazon** [comment]
Ok, I read the code and the problem is due to the fact `__GCC` is not a standard macro. I’ll provide a patch to fix this as soon as I can.

**Comment by martinweismann** [comment]
Thanks, @phaazon !

**Comment by phaazon** [comment]
You’re welcome. Nice timing! :D
