### ISSUE TITLE
CMesh let you add more nodes, faces and beams than the allow

### ISSUE THREAD

**Issue by qmuntal** [3MFConsortium/lib3mf#110]
I've found what seems to be a minnor inconsistency in the CMesh class:

The methods CMesh::addNode, CMesh:addFace and CMesh:addBeam throw an error if the number of elements added to m_Nodes, m_Faces and m_Beams is higher than NMR_MESH_MAXNODECOUNT, NMR_MESH_MAXFACECOUNT and NMR_MESH_MAXBEAMCOUNT respectively. 

This check is always done before adding the element to the paged vector, thus no error will be thrown when adding an element to a mesh that has exactly the maximum number of elements. On the other hand, the CMesh::checkSanity will return false in this situation.

This issue could be easily solved checking for higher or equal insteal of just higher before adding the element. The downside is that it would break backwards compatibility for files that live on the edge.

**Comment by martinweismann** [comment]
Good catch!
I updated the code to adhere to the core- and beamlattice-specifications.
https://github.com/3MFConsortium/lib3mf/pull/144
