### ISSUE TITLE
Internal material composition

### ISSUE THREAD

**Issue by CharlesFr** [3MFConsortium/lib3mf#126]
I understand materials can defined at the surface level and interpolated internally using barycentric coordinates. 

However, for my application I need to be able to define it arbitrarily throughout the internal volume.

Is there a workaround for this?

The element limit is 2^32 so providing I have less material setpoints than this number I could define each material volume with a tetrahedron? This seems like a sub-optimal solution though, especially given that I won't have any interpolation between my tetra's.

**Comment by martinweismann** [comment]
Your assessment is correct: the 3MF-specification https://github.com/3MFConsortium/spec_core/blob/master/3MF%20Core%20Specification.md#51-base-material only provides means to define mateirals at the surface of objects whereas its distribution within the volume is arbitrary .

You are also right about your workaround using tetrahedra (or, in fact, any closed shell), that this is very inefficient and ill-suited for materials that vary continuously throughout the model.

On the upside: The 3MF consortium is currently devising an extension to 3MF that allows to exactly specify materials and properties at any point within a model (which will exactly cover your use case!). However, it will take several months more until this is ready (and implemented in lib3mf...).

**Comment by pierre-leon** [comment]
Thanks @martinweismann good to hear that it's in the works.

**Comment by CharlesFr** [comment]
Can I ask if there's any update on this feature?

**Comment by martinweismann** [comment]
Hi @CharlesFr ,
there are news, indeed! The consortium has drafted a specification for defining custom distributions of properties within the volumes of objects. Simultaneously, we are developing an implementation for this extension within lib3mf (https://github.com/3MFConsortium/lib3mf/tree/volumetric, note: this branch is highly experimental).
No exact ETA, but we are getting closer...

**Comment by CharlesFr** [comment]
Thanks @martinweismann  - that's great to hear. Are you able to share this specification?
