### ISSUE TITLE
Improve 3mf read progress callback

### ISSUE THREAD

**Issue by qmuntal** [3MFConsortium/lib3mf#129]
The current 3mf progress callback have two drawbacks:

- The number of resources, build items, vertices, triangles, etc, cannot be known in advance, so the reported progress does not represent the real progress, but only a guess that works if there are few elements but is not representative at all if there are many elements (+20).

- The information inside each resource is not constant, maybe one resource has 20 triangles and another has 1 million, so it could happen that you have parsed the 98% of the 3mf in 1 minute but there is still missing one big resource that will take 5 minutes to parse.

A better approach could be to report the progress as the number of bits read from the decompressed model files divided by the total decompressed model files size. This way the progress would be more predictable and won't depend on the model composition.

As this would probably be a breaking change, the lib3mf v2 could be a good place to implement it.

**Comment by martinweismann** [comment]
This is correct. The progress handling of lib3mf is silly.
I suggest the following:
1. Calculate the _progress percentage_ according to the relative number of bytes read sofar (as you pointed out)
2. Still report the action the library performs (the _"ProgressIdentifier"_) to the client the way it is done now.

This way, we'll have the best of both worlds.

Thanks for your suggestion! We will add this for v2.

**Comment by qmuntal** [comment]
Agree on keeping the current action. 

When implementing it, I would suggest to check if you can remove the progress reporting from the element readers and centralize in the CModelReader_3MF::readStream, so the element readers only inform about which is the current stage to the main xml loop and at the end of each ElementClose (or at each element) you check if the number of read bytes is higher than the target one, moment when you execute the progress callback.

I have something similar implemented in https://github.com/qmuntal/go3mf/blob/master/io3mf/read.go#L198, but only to check if the user cancelled the parsing, if you want to take a look as a reference.
