### ISSUE TITLE
Some shortcomings/missing interfaces in lib3mf v2 alpha

### ISSUE THREAD

**Issue by shahchintan14** [3MFConsortium/lib3mf#132]
1. Couldn't find a way to set/get the default property of a mesh object.
2. Are international strings supported? Earlier version of lib3mf (v1.x) had utf8 versions of APIs dealing with strings.
3. No way of setting model metadata without namespace, type and mustPreserve attibute.Metadata outside the MetadataGroup element. (global metadata in 3mf model)
4. No interface corresponding to the old lib3mf_propertyhandler_removeproperty to remove triangle properties (color).

**Comment by martinweismann** [comment]
Thanks for your feedback, @shahchintan14 :

1. \+ 4. That was a bit of an oversight: default properties as well as removing properties are not yet exposed in v2. We shall fix this, soon.
2. All strings that go over the API are currently interpreted UTF8-strings. We might auto-generate additional UTF16 versions (like in v1.*) at some point again.
3. The MetaDataGroup-class in the API is simply a list of MetaData-class instances. It translates to a \<metadatagroup>-element with a list of \<metadata>-elements when used within a [build item](https://github.com/3MFConsortium/spec_core/blob/master/3MF%20Core%20Specification.md#3431-item-element) or [object resource](https://github.com/3MFConsortium/spec_core/blob/master/3MF%20Core%20Specification.md#chapter-4-object-resources) whereas it is simply used as a list of \<metadata>-elements (without an enclosing \<metadatagroup>-element) when used on a [ \<model> element](https://github.com/3MFConsortium/spec_core/blob/master/3MF%20Core%20Specification.md#34-model). Basically, this saves a couple of API calls on the Model-class.

**Comment by shahchintan14** [comment]
@martinweismann any idea when lib3mf v2.0 is going to be released for production? with fixes for all the reported issues?

**Comment by martinweismann** [comment]
We incorporated all your feedback into [v2.0.0-beta](https://github.com/3MFConsortium/lib3mf/releases/tag/v2.0.0-beta). A production-version should now take less than the 3 months it took us to get from alpha to beta...
