### ISSUE TITLE
lib3mf v2.0.0. alpha: Crash during destruction of CObject shared_ptr returned by CComponent::GetObjectResource()

### ISSUE THREAD

**Issue by shahchintan14** [3MFConsortium/lib3mf#134]
[lib3mf_debug.zip](https://github.com/3MFConsortium/lib3mf/files/3202546/lib3mf_debug.zip)

Version: lib3mf v2.0.0 alpha

A lib3mf based application, which tries to read 3mf file, crashes when PObject returned by CComponent::GetObjectResource() goes out of scope. (i.e. when it is destroyed.) Please use attached code (VS solution) and 3mf files to verify the problem.

Notably, a similar function CBuildItem::GetObjectResource() works fine.

**Comment by martinweismann** [comment]
Good catch. Thanks!
