### ISSUE TITLE
lib3mf v2.0.0 alpha: Does CColorGroup::AddColor check for duplicate colors before adding?

### ISSUE THREAD

**Issue by shahchintan14** [3MFConsortium/lib3mf#135]
The earlier version of lib3mf used to write only unique colors in 3mf color groups.

**Comment by martinweismann** [comment]
No, neither `CColorGroup::AddColor` nor `CColorGroup::SetColor` check for duplicate values of colors before adding and setting them, respectively.

There are two reasons for this:
1. v2 changed the way properties are handled in lib3mf:
  - In v1.* one directly sets a color to e.g. a triangle. During the serialization into a 3MF-file the color groups ere assembled on the fly and the `pid="*" p1="*"...` attributes are calculated from them.
 - v2 now works a bit closer to the datamodel (i.e. \<color>s in a \<colorgroup> form a `pid` and `pindex` pair), and one can (must?) build up the colors inside the colorgoup while adding them.
 - The reason for this change is mainly the support for multiproperties, which is much easier to do in the general space of `pid` and `pindex`, compared to the concrete notions of "colors", "material", "textures", ...
2. The specification does not forbid duplicate \<color>-entries in a \<colorgroup>. v2 allows these duplicates now. https://github.com/3MFConsortium/spec_materials/blob/master/3MF%20Materials%20Extension.md#chapter-2-color-groups
