### ISSUE TITLE
Beamlattice SetRepresentation doesn't work - lib3mf v2.0.0 alpha and older versions

### ISSUE THREAD

**Issue by shahchintan14** [3MFConsortium/lib3mf#136]
[Beamlattice_SetRepresentation.zip](https://github.com/3MFConsortium/lib3mf/files/3206965/Beamlattice_SetRepresentation.zip)
Please refer attached code/VS solution to recreate the problem.

CBeamLattice::SetRepresentation() does not set the representation mesh object the beam lattice.

**Comment by martinweismann** [comment]
Thanks for the notification. It's fixed now.
