### ISSUE TITLE
lib3mf v2.0.0 alpha: CAttachment::ReadFromBuffer() doesn't make a copy of the supplied buffer, which is lost before we finally go for serialization of 3mf model

### ISSUE THREAD

**Issue by shahchintan14** [3MFConsortium/lib3mf#137]
Earlier version of lib3mf v1.8.1 had lib3mf_attachment_readfrombuffer() which internally used to make copy of the supplied buffer. (See NMR_ImportStream_Memory.cpp Line 105)

On the other hand, lib3mf v2.0.0 alpha, just assigns the supplied buffer pointer to a data member of a class CImportStream_Shared_Memory. (See NMR_ImportStream_Shared_Memory.cpp Line 52).

<Edit> lib3mf v2.0.0 makes the copy of the buffer while serializing. But by then the buffer supplied is destroyed. <Edit>

Is this change intended?

**Comment by martinweismann** [comment]
Thanks, @shahchintan14 ! This change was not intended.
https://github.com/3MFConsortium/lib3mf/pull/138 restores the correct behaviour.

Cheers!

**Comment by martinweismann** [comment]
Oh, and btw: this behaviour is intended for ModelReader::ReadFromBuffer, as the buffer is only required throughout the process of reading the 3MF from the buffer.

(see https://github.com/3MFConsortium/lib3mf/issues/119)
