### ISSUE TITLE
<colorgroup> support?

### ISSUE THREAD

**Issue by phaazon** [3MFConsortium/lib3mf#14]
I’m trying to open a .3mf file which has color groups, but I can’t find a way to retrieve them via the API. Any idea? Thanks in advance.

**Comment by netfabb** [comment]
Hi Dimitri,

in the API, you have to create a PropertyHandler, which allows you to 
get and set all kinds of properties on a
triangle level. The colors do not have to be managed in groups, that 
will be done at import/export.

All the best,
  Alex

Am 15.02.2016 um 10:54 schrieb Dimitri Sabadie:
>
> I’m trying to open a .3mf file which has color groups, but I can’t 
> find a way to retrieve them via the API. Any idea? Thanks in advance.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/3MFConsortium/lib3mf/issues/14>.
>


--
Best regards

Dipl.-Math. Alexander Oster
CEO

netfabb GmbH
Eichenbühl 10
92331 Lupburg
Germany

Phone:  +49 94 92 60 16 40 0
Fax:    +49 94 92 60 16 40 9
Mail:   alexander.oster@netfabb.com
Web:    www.netfabb.com
Skype:  alexander.oster

CEO: Dipl.-Math. Alexander Oster
Court of jurisdiction: Amtsgericht Nuremberg HRB 25345
VAT-No.: DE264795045

You can always contact us at: info@netfabb.com

We are excited that netfabb is becoming part of Autodesk, Inc. While we work through this transition, you may see email and some areas of our business begin to merge with Autodesk while others are still processed by netfabb. Your personal data will not be transferred to Autodesk without your consent. We appreciate your patience during this integration, please let us know if you have questions about the integration process as it relates to our support of your business.

**Comment by phaazon** [comment]
Hm, so I have to create a `PropertyHandler` in order to get things? I’ll try that, thank you.

**Comment by alexanderoster** [comment]
Perfect, thanks! The idea is, that the PropertyHandler interface is the same, but you can easily use it for multi-channel properties.

All the best,
 Alex
