### ISSUE TITLE
lib3mf v2.0.0 alpha: extra blend method in multiproperties

### ISSUE THREAD

**Issue by shahchintan14** [3MFConsortium/lib3mf#140]
The 3MF materials extension says that the number of blendmethods in a multiproperties element must be one less than the number of layers in it.
lib3mf v2.0.0 asks to supply a blendmethod for each layer, (PMultiPropertyGroup::AddLayer) and also writes each of them in the 3mf model file.
In the following example there are 5 layers in the multiproperties element and blend methods are specified for each of them.

<m:multiproperties id="14" pids="2 7 9 11 13" blendmethods="mix mix mix mix mix">

Is this correct? Or should there be 4 blendmethods?

**Comment by martinweismann** [comment]
You are right, there should be 4 blendmethods.

https://github.com/3MFConsortium/lib3mf/pull/148 took care of this now.

Cheers!

**Comment by shahchintan14** [comment]
@martinweismann Looking at the code changes it seems the blendmethod supplied with first layer is ignored? So we are supposed pass the correct blendmethods for the subsequent layers?
I was shifting the blendmethods to left by 1 so far. Seems I do not need to do that anymore?

**Comment by martinweismann** [comment]
This is correct, the blendmethod of the first layer is ignored. Thus there is no need to shift methods to the left. I hope that works for you.

I think the current API regarding layers of multiproperties is minimalist but clear and it does capture the gist of what is defined in the materials-specification https://github.com/3MFConsortium/spec_materials/blob/master/3MF%20Materials%20Extension.md#chapter-5-multiproperties.
