### ISSUE TITLE
CBeamLattice: No method to set default cap mode?

### ISSUE THREAD

**Issue by shahchintan14** [3MFConsortium/lib3mf#150]
There is a way to set cap mode on individual beams, but couldn't find any interface to set cap mode on the entire beamlattice element. Should there be one in CBeamLattice class?

**Comment by martinweismann** [comment]
It is intended for lib3mf's beamlattices to not have default capmodes or properties.
According to 
https://github.com/3MFConsortium/spec_beamlattice/blob/master/3MF%20Beam%20Lattice%20Extension.md#11-beamlattice 
each beam can have a property and a capmode in the 3MF datamodel. The beamlattice pid and beamlattice capmode are purely an auxiliary encoding of these beam-properties and are not part of the datamodel. Thus, the "beamlattice-level-pid" and "beamlattice-level-capmode" are not part of the API. (I intentionally do not use the term "defaul pid").

There is currently a bigger discussion going on about whether the same should hold for "object-level pid" in the core specification. There, the sole role of "object level pid" is to serve as fallback for consumers does not support properties per triangle.
