### ISSUE TITLE
lib3mf2.0.0 beta: Exception thrown when writing mesh object without any object or triangle level property

### ISSUE THREAD

**Issue by shahchintan14** [3MFConsortium/lib3mf#151]
CWriter::WriteToFile throws NMR_ERROR_MISSINGDEFAULTPID when writing a 3mf file having mesh object with neither object nor triangle properties.

But since there are no triangle properties in the mesh, default property should not be required.
This problem could be because of recent change in NMR_ModelWriterNode100_Model.cpp Line 472, to write object level properties.  #147

**Comment by martinweismann** [comment]
well spotted. Will be resolved by https://github.com/3MFConsortium/lib3mf/pull/154
