### ISSUE TITLE
lib3mf 2.0 is not able to read 3mf files in older schema

### ISSUE THREAD

**Issue by shahchintan14** [3MFConsortium/lib3mf#155]
lib3mf 2.0 beta is not able to read 3mf files of schema http://schemas.microsoft.com/3dmanufacturing/2013/01.

There are still quite some files out there which follow the older schema of 3mf file format. Is there any way to read such files using lib3mf 2.0?

**Comment by martinweismann** [comment]
Re-enabled in https://github.com/3MFConsortium/lib3mf/pull/167
