### ISSUE TITLE
Can not see the beamlattice model

### ISSUE THREAD

**Issue by charlieputhedu** [3MFConsortium/lib3mf#159]
I download the latest lib3mf(v2.0.0-beta) and run the Example_BeamLattice, it generated a ".3mf " file which called "beamlattice.3mf",Other software such as Rhino6 or 3-matic can successfully read it but cannot see the generated entity. How can I see the generated entity?

![image](https://user-images.githubusercontent.com/51358474/61637434-18be3280-acca-11e9-81e8-9fc101c3cc21.png)

**Comment by charlieputhedu** [comment]
![image](https://user-images.githubusercontent.com/51358474/61679039-776dc580-ad37-11e9-83d5-7dfbd6d2dbea.png)
other examples can not open the file.

**Comment by charlieputhedu** [comment]
Could VTK render 3mf beamlattice??

**Comment by martinweismann** [comment]
Not all software supporting 3MF also supports the beamlattice extension.

Software that supports the beamlattice extension are e.g. Autodesk Netfabb Premium and nTopology's software. They certainly read the file "beamlattice.3mf" which is generated by Example_BeamLattice.
If Materialise 3-matic does not support this file, please contact their support.

I am not aware that VTK currently supports 3MF or it's beamlattice extension, but this would be a great addition to VTK.
