### ISSUE TITLE
Question about an error in Microsoft 3D builder

### ISSUE THREAD

**Issue by mvelayati** [3MFConsortium/lib3mf#16]
Hello,
I have created a .3mf file but when I open it in 3D builder(Microsoft's built-in app on windows 8 or above) it gives me this error:
"One or more objects are invalidly defined. Click here to repair."
I want to know what is causing this issue. 
This error never happened before for simple shapes, but this time my shape is fairly complicated with many objects in it.

Thanks!

**Comment by martinweismann** [comment]
If this is still relevant, please contact 3D builders support or try with https://www.autodesk.com/products/netfabb/free-trial  (this uses lib3FF, too).
