### ISSUE TITLE
3mf export does not work on big-endian

### ISSUE THREAD

**Issue by knielsen** [3MFConsortium/lib3mf#160]
lib3mf export on big-endian machines (mips, powerpc, hppa, s390) produces output files with wrong byte-order which cannot be read back in. This is seen in test failures from openscad in the Debian build-farm.

Looking in the source code CPortableZIPWriter::createEntry(), it seems to build an in-memory structure and write directly the in-memory binary representation to the output file. This will produce incorrect (byte-swapped) output on big-endian architectures.

I did not investigate deeply, but code-inspection of CPortableZipWriter matches with the failure seen in Debian. So unless something else is being done, it seems that currently lib3mf cannot write 3mf files on big-endian architectures?

(A quick look in the sources indicated that reading 3mf files uses libzip, so reading should be ok on big-endian).

lib3mf version: 1.8.1
OS: Debian GNU/Linux "buster" on big-endian architectures.

**Comment by t-paul** [comment]
What's the plan for the 1.8.x release? Is that going to be supported for a while in parallel to the new 2.x work? I'll try to have a look at packaging 2.x once there's a bit more spare time but it would be nice to know about the current release as this is going to be active for a while in Debian 10.

**Comment by martinweismann** [comment]
@t-paul : Our plan is to only release critical bugfixes for 1.8.x after the release of lib3mf v2.x .
Realistically, I expect at least one, but probably not many more releases on the v1.8 (or v1.9) line of lib3mf.

@knielsen : you are right, and I think we should be able to fix this easily.
Unfortunately, we do not have a CI setup for big-endian machines for lib3mf (Travis CI does not support any big endian target for lib3mf without doing a workaround via https://github.com/multiarch/qemu-user-static).

Which service are you using, and could you point me to the relevant configuration you are using in OpenSCAD? Thanks!

**Comment by knielsen** [comment]
@martinweismann :  Yes, big-endian is becoming rare these days.

For local test I am using a Debian installation running in qemu-system-mips. The Debian build infrastructure on https://buildd.debian.org/status/package.php?p=openscad has some "real" big-endian hosts, which is where the problem was originally detected in the openscad test suite.

The openscad configuration I'm using is the Debian packaging, ie. https://tracker.debian.org/pkg/openscad. Though to test the big-endian issue on lib3mf it should be sufficient to write out a 3mf file on big-endian and check that it can be read again; openscad is probably overkill for that.

**Comment by martinweismann** [comment]
Thanks for elaborating, @knielsen . I upted for a similar solution in https://github.com/3MFConsortium/lib3mf/pull/164.
