### ISSUE TITLE
Metadata support in lib3mf?

### ISSUE THREAD

**Issue by shahchintan14** [3MFConsortium/lib3mf#17]
Hi,

I have a question about lib3mf rather than an issue to report, but didn't know where to post.

The 3mf 1.0 format specifies that the <model> element can have metadata like Title, Designer, Description, etc.
Does lib3mf have support of writing this metadata in 3mf file?

Thanks & Regards,
Chintan

**Comment by prushenas** [comment]
Yes, you could add a new meta data to a 3MF model by using functions such as AddMetaData() or lib3mf_model_addmetadata().

**Comment by shahchintan14** [comment]
Thanks prushenas. That's exactly what I was looking for!
