### ISSUE TITLE
Does the error message thrown contain only error code?

### ISSUE THREAD

**Issue by charlieputhedu** [3MFConsortium/lib3mf#170]
![image](https://user-images.githubusercontent.com/51358474/64578867-5a5a8800-d3b3-11e9-9ebc-923b6a4759bb.png)
Does the error message thrown contain only error code? As you can see here, the error message thrown is not detailed.

**Comment by martinweismann** [comment]
you are right.
This has been improved in PR https://github.com/3MFConsortium/lib3mf/pull/171.

All internal errors (Error 5) will now also show the internal error message.

We'll fix the other error messages in the code generator we use (https://github.com/Autodesk/AutomaticComponentToolkit/) which will propagate to lib3mf at some point.
