### ISSUE TITLE
Mesh object repair / heal support

### ISSUE THREAD

**Issue by shahchintan14** [3MFConsortium/lib3mf#18]
Hello,

Currently, the library has functions to check whether a given mesh object is valid or not.
Does this library support repairing/healing an invalid mesh object too?

Thanks,
Chintan

**Comment by martinweismann** [comment]
Hi Chintan,

Lib3MF has some basic functionality to check whether meshes are sane ("IsManifoldAndOriented"). Maybe that already helps.
Mesh-repair is, however, out of the scope of the lib3MF library.

Cheers!
