### ISSUE TITLE
Memory leaks in libzip

### ISSUE THREAD

**Issue by dempo93** [3MFConsortium/lib3mf#180]
Which version of lib3mf are you using?

Version 2.0.0

Which operating system are you using?

Ubuntu 18.04, gcc 9.1

What did you do?

1) Compiled https://github.com/3MFConsortium/lib3mf/blob/master/SDK/Examples/Cpp/Source/ExtractInfo.cpp and checked for memory leaks with Valgrind. Executed multiple runs with different files.

2) Decided to use system libzip instead.
Installed libzip4 and disabled USE_INCLUDED_LIBZIP cmake option

What did you expect to see?

1) No leaks

2) ExtractInfo is compiled and runs correctly when linked against the system libzip

What  did you see instead?

1) Leaks
```
Leak_DefinitelyLost
360 bytes in 3 blocks are definitely lost in loss record 971 of 1,037
malloc
/home/user/project/dependencies-build/lib3mf/lib/lib3mf.so.2.0.0.0
/home/user/project/dependencies-build/lib3mf/lib/lib3mf.so.2.0.0.0
zip_fopen_index_encrypted
/home/user/project/dependencies-build/lib3mf/lib/lib3mf.so.2.0.0.0
/home/user/project/dependencies-build/lib3mf/lib/lib3mf.so.2.0.0.0
/home/user/project/dependencies-build/lib3mf/lib/lib3mf.so.2.0.0.0
/home/user/project/dependencies-build/lib3mf/lib/lib3mf.so.2.0.0.0
/home/user/project/dependencies-build/lib3mf/lib/lib3mf.so.2.0.0.0
/home/user/project/dependencies-build/lib3mf/lib/lib3mf.so.2.0.0.0
/home/user/project/dependencies-build/lib3mf/lib/lib3mf.so.2.0.0.0
lib3mf_reader_readfromfile
```
2) ExtractInfo is compiled but every run terminates with the error `symbol lookup error: /home/user/project/dependencies-build/lib3mf/lib/lib3mf.so.2: undefined symbol: zip_error_init`

**Comment by Tradias** [comment]
Compiling with clang-9 also produces this warning which might be related:

```
/lib3mf/Source/Libraries/zlib/inflate.c:1507:61: warning: shifting a negative signed value is undefined [-Wshift-negative-value]
    if (strm == Z_NULL || strm->state == Z_NULL) return -1L << 16;
                                                        ~~~ ^
```

**Comment by martinweismann** [comment]
Hi @dempo93 ,
thanks for bringing this up.
Regarding
1. https://github.com/3MFConsortium/lib3mf/pull/190 should fix this problem. In addition, I will add memory checking the integration tests via `valgrind` to CI in the long run.
2. Can you try again with the latest develop branch? I think that https://github.com/3MFConsortium/lib3mf/pull/185 fixed this.

**Comment by Tradias** [comment]
I can confirm that the current develop branch fixes both 1. and 2.

**Comment by martinweismann** [comment]
Thank you @Tradias  and @dempo93 .
BTW: https://github.com/3MFConsortium/lib3mf/pull/192 will add valgrind to the automatic builds on travis.
