### ISSUE TITLE
Error when compiling with node-gyp for node

### ISSUE THREAD

**Issue by artemzakharov** [3MFConsortium/lib3mf#181]
When I run `node-gyp rebuild --verbose` with the new version of the library, I get this error:
```
"C:\...\build\binding.sln" (default target) (1) ->
"C:\...\build\lib3mf_nodeaddon.vcxproj" (default target) (2) ->
(ClCompile target) ->
  ..\extra-deps\lib3mf\lib3mf_dynamic.cc(368): error C2440: 'initializing': cannot convert from 'void *' to 'wchar_t *' [C:\...\build\lib3mf_nodeaddon.vcxproj]

    94 Warning(s)
    1 Error(s)
```

**Comment by Ugzuzg** [comment]
@artemzakharov, is node addon code public?

**Comment by martinweismann** [comment]
Hi @artemzakharov ,
deos it work, if you manually change the line to:
`
wchar_t* wsLibraryFileName = (wchar_t* )malloc(nBufferSize*sizeof(wchar_t));
`

Also:
the node bindings are tested against
```
node -v
v8.12.0
```
later versions have removed some functionality. We might update the node bindings to work with the latest version of node/v8.

@Ugzuzg : the are inside the folder Bindings/NodeJS within the binary release https://github.com/3MFConsortium/lib3mf/releases/download/v2.0.0/lib3mf_sdk_v2.0.0.zip

**Comment by Ugzuzg** [comment]
@martinweismann, `LoadLib3MF` doesn't pass the args to `CLib3MFWrapper::NewInstance`, which means `CLib3MFWrapper::New` always gets the default value for `sLibraryName`:
```C++
            std::string sLibraryName = "lib3mf.dll";
```
Had to amend that for myself to get the constructor working.

**Comment by martinweismann** [comment]
Thanks, @Ugzuzg .
Can you share the code that passes the argument through? Or did you just change the path inside the binding file?

Just for a bit of context: we actually do not write the NodeJS binding as part of lib3mf. Instead, it is generated through https://github.com/Autodesk/AutomaticComponentToolkit . In fact all bindings are generated by this tool, which is the only practical way to maintain the different language-bindings. We will port any feedback you provide here back into this code generator.

**Comment by Ugzuzg** [comment]
@martinweismann, here's a diff:

```diff
diff --git a/src/lib3mf_dynamic.cc b/src/lib3mf_dynamic.cc
index 73064dd..8358499 100644
--- a/src/lib3mf_dynamic.cc
+++ b/src/lib3mf_dynamic.cc
@@ -40,6 +40,7 @@ Interface version: 2.0.0
 #else // _WIN32
 #include <dlfcn.h>
 #endif // _WIN32
+#include <cstddef>
 
 Lib3MFResult InitLib3MFWrapperTable(sLib3MFDynamicWrapperTable * pWrapperTable)
 {
diff --git a/src/lib3mf_nodeaddon.cc b/src/lib3mf_nodeaddon.cc
index 8410060..7e20edc 100644
--- a/src/lib3mf_nodeaddon.cc
+++ b/src/lib3mf_nodeaddon.cc
@@ -36,6 +36,7 @@ Interface version: 2.0.0
 
 #include <node.h>
 #include "lib3mf_nodewrapper.h"
+#include <cstddef>
 
 using namespace v8;
 
@@ -43,7 +44,7 @@ void LoadLib3MF (const FunctionCallbackInfo<Value>& args)
 {
     Isolate* isolate = args.GetIsolate();
     HandleScope scope(isolate);
-    args.GetReturnValue().Set (CLib3MFWrapper::NewInstance());
+    args.GetReturnValue().Set (CLib3MFWrapper::NewInstance(args));
 }
 
 void InitAll(Handle<Object> exports, Handle<Object> module)
diff --git a/src/lib3mf_nodewrapper.cc b/src/lib3mf_nodewrapper.cc
index e728fbd..504ea58 100644
--- a/src/lib3mf_nodewrapper.cc
+++ b/src/lib3mf_nodewrapper.cc
@@ -36,6 +36,7 @@ Interface version: 2.0.0
 
 #include <node.h>
 #include "lib3mf_nodewrapper.h"
+#include <cstddef>
 
 
 using namespace v8;
@@ -9963,13 +9964,15 @@ void CLib3MFWrapper::New(const FunctionCallbackInfo<Value>& args)
     }
 }
 
-Local<Object> CLib3MFWrapper::NewInstance ()
+Local<Object> CLib3MFWrapper::NewInstance (const FunctionCallbackInfo<Value>& args)
 {
     Isolate* isolate = Isolate::GetCurrent();
     HandleScope scope(isolate);
     Local<Function> cons = Local<Function>::New(isolate, constructor);
     Local<Object> instance;
-    cons->NewInstance(isolate->GetCurrentContext()).ToLocal(&instance);
+    const int argc = 1;
+    Local<Value> argv[argc] = { args[0] };
+    cons->NewInstance(isolate->GetCurrentContext(), argc, argv).ToLocal(&instance);
     return instance;
 }
 
diff --git a/src/lib3mf_nodewrapper.h b/src/lib3mf_nodewrapper.h
index 866eb92..c657eb6 100644
--- a/src/lib3mf_nodewrapper.h
+++ b/src/lib3mf_nodewrapper.h
@@ -961,7 +961,7 @@ public:
     CLib3MFWrapper ();
     ~CLib3MFWrapper();
     static void Init();
-    static v8::Local<v8::Object> NewInstance();
+    static v8::Local<v8::Object> NewInstance(const v8::FunctionCallbackInfo<v8::Value>& args);
 };
 
 #endif // LIB3MF_NODEWRAPPER_H
```

**Comment by martinweismann** [comment]
Thank you! This will enter the next ACT release and then go into a lib3mf 2.1.0 release
https://github.com/Autodesk/AutomaticComponentToolkit/commit/ebb2b80af2de93894c450640d387b2ce8ccc298a .

Also note that the new NodeJS bindings will work for Node v12.13 https://nodejs.org/en/download/releases/ / https://nodejs.org/en/blog/release/v12.13.0/ which appears to be the LTS version advocated by the nodejs foundation.

@Ugzuzg : if you have a small example for nodejs, that is more advanced than the one I used to try this out (https://github.com/3MFConsortium/lib3mf/tree/develop/SDK/Examples/NodeJS) please share it and I will include it into the next binary SDK.

**Comment by artemzakharov** [comment]
Sorry that I wasn't able to come back to this issue, is everything working now? Or do I need to get into debugging this again? I'm not acquainted with C++ very well, so I'm having a hard time telling if comments made by @Ugzuzg are related to my original issue or not.

**Comment by martinweismann** [comment]
@artemzakharov :
as a quick workaround, you should be able to get the NodeJS binding to compile by changing
```wchar_t* wsLibraryFileName = malloc(nBufferSize*sizeof(wchar_t))```
to
```wchar_t* wsLibraryFileName = (wchar_t* )malloc(nBufferSize*sizeof(wchar_t))```
in `lib3mf\lib3mf_dynamic.cc`.
If this does not work, please be patient. In the next release of lib3mf (should be bugfixes only) we will include this change as well as update the binding to work with Node v12.13, the Long Time Support version.

**Comment by artemzakharov** [comment]
No worries, this isn't a blocker for me, more than happy to just use the old version while this kink is worked out, which it sounds like it will be in the next version - just wanted to make sure that it was still about the original issue.

**Comment by martinweismann** [comment]
@artemzakharov : yes, this `malloc`-kink and the issue of the binary's path will be fixed in the next release. There is another issue with inherited classes that needs to be fixed in the next release, too: https://github.com/Autodesk/AutomaticComponentToolkit/issues/77
