### ISSUE TITLE
Node bindings inheritance

### ISSUE THREAD

**Issue by Ugzuzg** [3MFConsortium/lib3mf#188]
Node bindings don't inherit from parent classes, so for example `CObjectIterator` only has its own methods (`GetCurrentObject`), and you cannot call `MoveNext` on it, which results in objects being inaccessible.

**Comment by martinweismann** [comment]
Hi @Ugzuzg ,
i started an issue for this in the ACT-repo: https://github.com/Autodesk/AutomaticComponentToolkit/issues/77.
Let's follow it up there. The fix will be ported back to lib3mf when updating ACT.
Thanks!
