### ISSUE TITLE
2d implementation

### ISSUE THREAD

**Issue by RazaGR** [3MFConsortium/lib3mf#189]
I am using OpenCV to read the image and convert vertices to 3d. Is it possible to load a 2d image using lib3mf and add a Z height to it? I found an example on how to load image as a texture in  [fnLoadModelTexture function](https://github.com/3MFConsortium/lib3mf/blob/master/SDK/Examples/Cpp/Source/TextureCube.cpp) but couldn't find any info if it's possible to add a Z height on the image/texture.

If it's possible to increase the Z height of image/texture with lib3mf default functions, could I see an example code, please?

Thanks

**Comment by martinweismann** [comment]
Hi @RazaGR ,
such functionality is not part of lib3mf. The 3MF consortium might add displacement- or bumpmapping to the 3MF standard (and subsequently to lib3mf) at some point. In the meantime, you will need to perform height-mapping with a custom implementation on top of lib3mf's built in datastructures (2D textures and Lib3MF::sPosition) or using a different toolkit.
Best wishes
