### ISSUE TITLE
No interfaces for writing PrintTicket in 3MF file

### ISSUE THREAD

**Issue by shahchintan14** [3MFConsortium/lib3mf#19]
I was looking for API functions to write print ticket in 3MF file. But I didn't find any.

Does lib3MF support writing print tickets?

If no, why? Is there any plan to support this in future?

Regards,
Chintan

**Comment by martinweismann** [comment]
Hi @shahchintan14 

There is no specific API for adding print tickets, as this is fully covered by the attachment API.

Steps are:
1. Add a custom content type "application/vnd.ms-printing.printticket+xml" to the model (`lib3mf_model_addcustomcontenttypeutf8`)
2. Add an attachment to the root model of your 3MF package with the correct relationship type 
`"http://schemas.microsoft.com/3dmanufacturing/2013/01/printticket"` via `lib3mf_model_addattachmentutf8`
3. Read the attachment-souce into the 3MF model via `lib3mf_attachment_readfromfileutf8`

Have a look at the "UnitTest_Attachments.cpp"-file. This demonstrates how to add attachments to a model.

Assembling the content of the print ticket is, however, still up to the user.
