### ISSUE TITLE
errors while building with vs2017 / vs2019

### ISSUE THREAD

**Issue by kcris** [3MFConsortium/lib3mf#195]
Hi,

I tried to build v2.0.0 using VS 2017

```
git checkout tags/v2.0.0 -b lib3mf-tag-v2.0.0
mkdir build
cd build
cmake -G "Visual Studio 15 2017 Win64" ..
```

and I get build errors about some files that do not exist:
```
3>d:\lib3mf\source\api\lib3mf.cpp(36): fatal error C1083: Cannot open include file: 'lib3mf_abi.hpp': No such file or directory

3>d:\lib3mf\include\api\lib3mf_attachment.hpp(35): fatal error C1083: Cannot open include file: 'lib3mf_interfaces.hpp': No such file or directory

3>d:\lib3mf\include\api\lib3mf.cpp(37): fatal error C1083: Cannot open include file: 'lib3mf_interfaceexception.hpp': No such file or directory
...
```

So at least these 3 files are not found
* lib3mf_abi.hpp
* lib3mf_interfaces.hpp
* lib3mf_interfaceexception.hpp

I get the same errors 
* if I use your script to generate VS2017 files (`cmake\GenerateVS2017.bat`)
* if I use the master branch
* if I use VS2019

Any idea?
thanks

edit: on linux it compiles, it seems that there are some `Autogenerated` files that are not created on windows

**Comment by kcris** [comment]
solved by building
- lib3mfACT (first module)
- lib3mf (second module)

**Comment by martinweismann** [comment]
Hi @kcris ,
I am under the impression, that building the whole solution in VS or using `cmake --build .` builds the individual projects in a correct order. Does that work?
