### ISSUE TITLE
Calls to COM interfaces return objects with refCount = 0

### ISSUE THREAD

**Issue by StSimmons** [3MFConsortium/lib3mf#2]
The COM contract states that the function should call AddRef before returning the COm object to the caller. The caller is then responsible for calling Release. (See: https://msdn.microsoft.com/en-us/library/ms692481.aspx)

However, it seems that lib3mf does not do this and sets all Com Pointers to refcount = 0, requiring the caller to call AddRef (against the COM contract).

Is this expected? Am I missing something?

**Comment by martinweismann** [comment]
Please see https://github.com/3MFConsortium/lib3mf/issues/51
