### ISSUE TITLE
Broken link in README.md

### ISSUE THREAD

**Issue by lordofhyphens** [3MFConsortium/lib3mf#20]
http://3mf.io/what-is-3mf/3mf-specification/ is a dead link.

**Comment by ofloveandhate** [comment]
still dead one month later

**Comment by jrkst34** [comment]
Hi guys,

Please visit the main site at [http://3mf.io](http://3mf.io) and browse to the Specification link at the top of the screen.  The link you have posted is no longer active.

**Comment by ofloveandhate** [comment]
and yet, this dead link appears here:
https://github.com/3MFConsortium/lib3mf

**Comment by martinweismann** [comment]
Thanks @adrianlannin who has fixed this in the meantime.
