### ISSUE TITLE
Upgrade version from 1.2 to 2.0 mf library issues

### ISSUE THREAD

**Issue by vgurav** [3MFConsortium/lib3mf#200]
HI ,
we are upgrading version from 1.1 to 2.0.0 3MF library. i found some issues when we are upgrading to version 2.0 For ex. 
API lib3mf_meshobject_setgeometry taking argument MODELMESHVERTEX in previous version 1.1 now its taking as sLib3MFPosition.Whatever previous(version 1.1) API we are using its not supported in version 2.0 because of change in argument in signatures of C-bindings.
Should we have to  rewrite when to upgrade 2.0?
if its supported for previous version 1.1 then Could you please mention how to support it.

Following functions also i didnt found in version 2.0.
lib3mf_model_addmetadata
lib3mf_object_createdefaultpropertyhandler
lib3mf_defaultpropertyhandler_setcolor
lib3mf_meshobject_createpropertyhandler
lib3mf_propertyhandler_setsinglecolor
lib3mf_meshobject_setbeamlattice_minlength
lib3mf_meshobject_setbeamlattice_capmode
lib3mf_meshobject_setbeamlattice_clipping
lib3mf_meshobject_setbeamlattice_radius
lib3mf_meshobject_addbeam
lib3mf_model_getmetadatacount
lib3mf_model_getmetadatakey
lib3mf_model_getmetadatavalue
lib3mf_defaultpropertyhandler_getpropertytype
lib3mf_defaultpropertyhandler_getbasematerial
lib3mf_model_getbasematerialbyid
lib3mf_model_getbasematerialbyid
lib3mf_basematerial_getdisplaycolor
lib3mf_defaultpropertyhandler_getcolor

Waiting for your reply.

**Comment by martinweismann** [comment]
Hi @vgurav ,
lib3mf v2 provides a new API.

The main differences are:
1. there are now object-oriented bindings for other languages than C, too, e.g. C++ and python. The code examples for for C++ in the SDK (https://github.com/3MFConsortium/lib3mf/releases/download/v2.0.0/lib3mf_sdk_v2.0.0.zip) best illustrate the new API. If you still want (or need) to use the C bindings, you will find that  they are similar, but not compatibly to v1.*'s API. A full reference to the new API is https://lib3mf.readthedocs.io/en/master/source/Cpp/LandingPage.html 
2. Properties are now handled differently: the propertyhandlers have been removed. Instead, one can directly obtain the property IDs and Indices from triangles and objects via GetTriangleProperties.

Does that make sense?
