### ISSUE TITLE
3mf file - cannot associate mesh with material (if metadata is used)

### ISSUE THREAD

**Issue by kcris** [3MFConsortium/lib3mf#201]
Hi,

I am exporting some meshes to a .3mf file using lib3mf v2.0.0.

I am able to get something like this in the output xml

```
<basematerials id="2">
  <base name="Material A" displaycolor="#AA000000"/>
</basematerials>

<basematerials id="4">
  <base name="Material B" displaycolor="#0032AA00"/>
</basematerials>

<object id="1" name="Mesh1" type="model" p:UUID="...">
  <mesh>
  ....
  <mesh/>
<object/>

<object id="3" name="Mesh2" type="model" p:UUID="...">
  <mesh>
  ....
  <mesh/>
<object/>
```

I want to associate one mesh with one specific material.

Is this possible in 3mf?

I am unable to find a function that allows me to say: for a given mesh X, the associated material is Y.
I need something like

`mesh1->setBaseMaterialsId(4); //e.g. to associate mesh1 with the material B`

Thanks

**Comment by martinweismann** [comment]
Hi Chris,

this works via the setting of properties.
```
PModel model = wrapper->CreateModel();

PBaseMaterialGroup pBaseMaterial = model->AddBaseMaterialGroup();
Lib3MF_uint32 nBaseMaterialID = pBaseMaterial->AddMaterial("PLA Blue", wrapper->FloatRGBAToColor(.0f, .0f, 1.0f, 1.0f));

PMeshObject meshObject = model->AddMeshObject();
meshObject->SetObjectLevelProperty(pBaseMaterial->GetResourceID(), nBaseMaterialID);
```
Properties of all or individual (or all) triangles are set via `meshObject->SetTriangleProperties` (or `meshObject->SetAllTriangleProperties`).

**Comment by kcris** [comment]
Hi,
I tried that function and it does not save anything

// Add base material group to lib3mf model
Lib3MF_BaseMaterialGroup pModelBaseMaterial3MF;
lib3mf_model_addbasematerialgroup(m_spModel3MF, &pModelBaseMaterial3MF);

// Add material with name and RGB information to base material group
Lib3MF_uint32 propertyId = 0;
lib3mf_basematerialgroup_addmaterial(pModelBaseMaterial3MF, materialName, color, &propertyId);

// Get basematerial resource ID
Lib3MF_uint32 ResourceID;
lib3mf_resource_getresourceid(pModelBaseMaterial3MF, &ResourceID); 
lib3mf_meshobject_setobjectlevelproperty(spMesh3MF, ResourceID, propertyId);

**Comment by martinweismann** [comment]
Oh, I see.

Does your example work as expected if you do not add metadata to the mesh?

**Comment by kcris** [comment]
Hi, 
I can confirm now, 
* the association between mesh and basematerial does not work if metadata is saved
* the association between mesh and basematerial does work if no metadata is saved

see examples below

1. when metadata is saved

```
		<basematerials id="2">
			<base name="Similar to Aluminum 7050-T7651" displaycolor="#AA000000"/>
		</basematerials>
		<object id="1" name="Segment #1" type="model" p:UUID="e8086963-06be-4fb4-8db7-20d7c4ef1f11">
			<metadatagroup>
				<metadata name="cura:extruder_nr" type="string" preserve="1">1</metadata>
				<metadata name="cura:infill_mesh" type="string" preserve="1">True</metadata>
				<metadata name="cura:infill_sparse_density" type="string" preserve="1">20</metadata>
			</metadatagroup>
			<mesh>...
```


when no metadata is saved 

```
		<basematerials id="2">
			<base name="Similar to Aluminum 7050-T7651" displaycolor="#AA000000"/>
		</basematerials>
		<object id="1" name="Segment #1" type="model" p:UUID="5c945eaf-4f56-45a2-a560-ff342fefa60a" pid="2" pindex="0">
			<mesh>
```

note the presence of: pid and pindex attributes - inside the object element


Note that:
* same mesh was used
* I used lib3mf v2.0.0 for export (the C api, see my code in my previous message)

Thanks

**Comment by martinweismann** [comment]
Should be fixed in lib3mf v2.1.1

**Comment by kcris** [comment]
@martinweismann thanks a lot!
any idea when 2.1 will be released?

**Comment by martinweismann** [comment]
Last touches ...
