### ISSUE TITLE
Exception while loading sample 3MF file (duplicated metadata entries)

### ISSUE THREAD

**Issue by jbherdman** [3MFConsortium/lib3mf#209]
When trying to load one of the 3MF files from the `3mf-samples` repository, lib3mf gives me an exception.  Specifically, this issue can be seen when trying to load the file found at:  https://github.com/3MFConsortium/3mf-samples/blob/master/examples/material/dodeca_chain_loop_color.3mf

The problem, for this file, is that there are two "Description" metadata entries.

Inside `CModelReaderNode_Model::ReadMetaDataNode()`, there is an if-clause that detects the duplicated metadata, and produces a `MODELREADERWARNING_DUPLICATEMETADATA` warning.  However, the code proceeds to throw an exception a few lines later during the call to `m_pModel->addMetaData()`.  This exception (`NMR_ERROR_DUPLICATEMETADATA`) prevents the file from loading.

As I see it, there are two reasonable solutions:
  1)  After generating the `MODELREADERWARNING_DUPLICATEMETADATA`, the `ReadMetaDataNode()` method could just return.  This means that the "first copy" of the duplicated metadata would be preserved.  The warning would be generated, but no exception would occur, allowing the file-load to complete.
  2)  After generating the `MODELREADERWARNING_DUPLICATEMETADATA`, the `ReadMetaDataNode()` method could remove the existing/conflicting metadata entry.  That means that the "second copy" (or "Nth copy") of the duplicated metadata would replace the original data.  The warning would be generated, but no exception would occur, allowing the file-load to complete.

Either way, it seems like more or less a one line fix, but it does require a "policy decision" to be made.  (Does lib3mf want to keep the first copy of the duplicated data, or the final copy?)

**Comment by martinweismann** [comment]
Hi @jbherdman ,

thank you for your contribution.

According to the core specification, meta data names must be unique:
- https://github.com/3MFConsortium/spec_core/blob/1.2.3/3MF%20Core%20Specification.md#341-metadata
- thus, the intent is that lib3mf handles this accordingly.

Thus option 1 of you suggestions would be the right approach.
Can you change you PR accordingly?

In the mean time, I will take the first part of you PR https://github.com/3MFConsortium/lib3mf/pull/210/files# which fixes https://github.com/3MFConsortium/lib3mf/issues/197 and https://github.com/3MFConsortium/lib3mf/issues/201 and copy it into develop.

Thanks!

**Comment by jbherdman** [comment]
Luckily for us, that is already the approach taken in my existing PR.

Technically, my PR moves everything after the warning's `if` into an `else` block, rather than forcing a `return;` onto line 160.  It is functionally equivalent, but seemed more "in the style of" the surrounding code.  Alternately, feel free to just add a "return;" directly after the `addWarning()` on line 159, instead of picking up the remainder of my PR.

**Comment by martinweismann** [comment]
Hi @jbherdman ,
you are right. I was not able to change your PR easily, so I moved your fix onto https://github.com/3MFConsortium/lib3mf/pull/216.

Will be part of v2.1.0.
Thanks again!
