### ISSUE TITLE
how to run the lib3mf-examples on linux

### ISSUE THREAD

**Issue by crurui** [3MFConsortium/lib3mf#21]
I want to make use of that 3mf converter on ubuntu, but I really know little.
https://github.com/3MFConsortium/lib3mf-examples
I fail to make that makefile in GCC……

**Comment by ofloveandhate** [comment]
i second this.  

3mf is garbage unless properly supported on free operating systems.

**Comment by t-paul** [comment]
Actually lib3mf works fine on Linux, the latest code works well and is about to be integrated in https://github.com/openscad/openscad/pull/1802.

If you have problems, I'd suggest to write a proper report which specifically shows what was run and what the issues occurred.

**Comment by ofloveandhate** [comment]
fair enough.  i was indeed successful in compiling lib3mf itself with gcc / clang on my mac.  the examples, on the other hand...  not so much.  see [issue 3](https://github.com/3MFConsortium/lib3mf-examples/issues/3) for the examples.

**Comment by crurui** [comment]
Thanks, I'll have a try

**Comment by ofloveandhate** [comment]
@crurui i was also eventually successful in compiling the Converter example, and it works great.  i converted a complicated model earlier today with it.  again, see https://github.com/3MFConsortium/lib3mf-examples/issues/3

**Comment by crurui** [comment]
The discussions and your conclusions are great, thanks to them I got that object file.
But when I tried to run that by ./Converter.o 
it told me "cannot execute binary file" Somebody says maybe there is something wrong with the encoding,while I used the utf-8
Honestly,  I'm totally new……

**Comment by ofloveandhate** [comment]
.o is not executable.  it's an object file, which is stitched together with other parts to make the executable.  
if compilation finished, there is a folder from that path `bin/Release`, which contains `Converter`, which is what you want to run.

**Comment by ofloveandhate** [comment]
please note that the compilation of these examples is not typical of free software on linux, which often use Autotools, CMake, or another build system, perhaps SCons or some such.  With the autotools, it goes `./configure` `make` `make install`, which solves these problems for you, by finding dependencies, and providing a mechanism for installing the software.

**Comment by crurui** [comment]
I have thought it was in object folder……I make it, Thank you all for the kindness！
