### ISSUE TITLE
Pkg Config is not built

### ISSUE THREAD

**Issue by aconz2** [3MFConsortium/lib3mf#224]
It looks like the pkg config file is not being built as it was removed here https://github.com/3MFConsortium/lib3mf/commit/a32e2179e47e17601fb87e898f5a010b71238d98#diff-af3b638bc2a3e6c650974192a53c7291L147-L148

In order to get it back in the `project(lib3mf)` in CMake will also need a `VERSION`. Happy to send a PR for this, but wanted to check and see what the situation was.

**Comment by martinweismann** [comment]
Hi @aconz2 , you are right, the switch from v1.* to v2 improved a lot, but also changed and broke other existing features of the pipelines around lib3mf. We would like to get that back.

Please create a PR that makes the pkg config again, and add some description how to test the change.
Thanks!

**Comment by martinweismann** [comment]
Thank you @aconz2 !
