### ISSUE TITLE
Add Encrypted File Relationship to encrypted parts and models

### ISSUE THREAD

**Issue by feliperoos** [3MFConsortium/lib3mf#228]
As stated by Secure Content spec item 3.3, 

"OPC parts that are encrypted MUST be associated with the package root through a Encrypted File relationship, and each SHOULD have an entry in the Key Store. If a custom OPC part is not referenced by a Encrypted File relationship it is assumed they are not encrypted and MUST NOT be any entry in the Key store associated to the file"

@martinweismann and @jordig100 I think this is one left over we forgot to add. Just have a question: the text mention **package root**. I just want to make sure that the relationship to be added is **not** on the package root **model** rels, rather at 'package root' rels (the sample provided makes it a bit confusing as external models aren't referenced from the package root rels).

If that's the case, we've the ability to add this relationship to the root model when we detect a part must be wrapped for encryption, 

https://github.com/3MFConsortium/lib3mf/blob/8d4a912667520721f24619d9adb1b42558443a17/Source/Model/Writer/NMR_KeyStoreOpcPackageWriter.cpp#L140-L145

Another option would be to have it right before we finish writing the package

https://github.com/3MFConsortium/lib3mf/blob/8d4a912667520721f24619d9adb1b42558443a17/Source/Model/Writer/NMR_KeyStoreOpcPackageWriter.cpp#L162-L168

Let me now what you think.

**Comment by jordig100** [comment]
Hi @feliperoos, this is already captured in the issue: https://github.com/3MFConsortium/spec_securecontent/issues/12

I think the asnwer is just to remove the "root" word from that sentence.

In the following link you an find the proposed change: https://github.com/3MFConsortium/spec_securecontent/blob/dev/3MF%20Secure%20Content.md#33-encrypted-file-relationship
