### ISSUE TITLE
CI setup does not work anymore

### ISSUE THREAD

**Issue by martinweismann** [3MFConsortium/lib3mf#235]
Reason:
travis ci's free tier (https://docs.travis-ci.com/user/billing-faq/#what-if-i-am-building-open-source) does not offer a suitable model any more. They have a credit limit that lib3mf has exceeded.

Look into a different CI system.

**Comment by qmuntal** [comment]
A lot of projects are moving to GitHub Actions. It is free, with "unlimited" resources and supports Windows agents.

I will land a PR with the migration to GitHub Actions to see if it is working fine for our use case.

**Comment by martinweismann** [comment]
That would be brilliant!

**Comment by martinweismann** [comment]
Thank you @qmuntal ! https://github.com/3MFConsortium/lib3mf/pull/241
