### ISSUE TITLE
Secure content spec is always marked as required

### ISSUE THREAD

**Issue by qmuntal** [3MFConsortium/lib3mf#238]
As of lib3mf 2.1.0 all models are encoded with the secure content extension marked as required in the `requiredextensions` attribute.

Looking at the code I see that there is a check to see if it is really required or not:

https://github.com/3MFConsortium/lib3mf/blob/cc19da48d05eb9f4e9d23a8358d1cd5386831f1f/Source/Model/Writer/v100/NMR_ModelWriterNode100_Model.cpp#L155-L162

but this check returns `true` in all cases as `m_pKeyStore` is always initialized in the `Model` constructor.

Snippet of `RequireExtension`:

https://github.com/3MFConsortium/lib3mf/blob/cc19da48d05eb9f4e9d23a8358d1cd5386831f1f/Source/Model/Classes/NMR_Model.cpp#L1213-L1217

If this issue is confirmed then all 3mf's generated by lib3mf v2.1.0 will require a consumer that supports the secure content spec, even when it is not necessary.

@feliperoos @martinweismann

**Comment by martinweismann** [comment]
Great find @qmuntal . I can confirm that problem.

It looks like this would fix the problem:
```
if (sExtension == XML_3MF_NAMESPACE_SECURECONTENTSPEC) {
	if (m_pKeyStore.get() != nullptr) {
		return !m_pKeyStore->empty();
	}
}
```
