### ISSUE TITLE
Calling lib3mf_createmodel twice causes exception after call to CoInitialize()

### ISSUE THREAD

**Issue by igfraga** [3MFConsortium/lib3mf#24]
CoInitialize returns S_FALSE when called a second time but that is not an error. lib3mf considers it an error and throws an exception.

https://msdn.microsoft.com/en-us/library/windows/desktop/ms678543(v=vs.85).aspx

**Comment by netfabb** [comment]
I see. The handling in lib3MF is incorrect then.

As far as I understand, we need to balance each call (including the onces that return S_FALSE) with a call to CoUninitialize();

How about we change the lib3mf_createmodel to
```c++
LIB3MF_DECLSPEC LIB3MFRESULT lib3mf_createmodel(_Outptr_ PLib3MFModel ** ppModel) {
  ...
  HRESULT hResult = CoInitialize(NULL);
  if (hResult != LIB3MF_OK) {
    if (hResult == S_FALSE) {
      // The COM library is already initialized on this thread. It needs to be balanced with a call to
      CoUninitialize();
    }
    else
      throw CNMRException_Windows(NMR_ERROR_COULDNOTINITITALIZECOM, hResult);
  }
...
}
```
This way, we do not need the initialize flag anymore, either.

**Comment by martinweismann** [comment]
Fixed as described above.
