### ISSUE TITLE
Updated Project files

### ISSUE THREAD

**Issue by ilan100** [3MFConsortium/lib3mf#26]
In latest 3MF code there is no "Project" folder containing the project and solution files.
I am trying to build the new code with the old Project files but it does not build: compiles but with link errors (for NMR objects)
Is it possible to update the project files to the new code? (supporting VS2015)

**Comment by alexanderoster** [comment]
Hi Ilan,

you can now use cmake (https://cmake.org/) to create project files for any platform.

Best,
 Alex

**Comment by ilan100** [comment]
Hi Alex,
Thanks a lot
Ilan
