### ISSUE TITLE
Incorrect conditional in NMR_ModelReaderNode100_Object.cpp

### ISSUE THREAD

**Issue by knielsen** [3MFConsortium/lib3mf#262]
In NMR_ModelReaderNode100_Object.cpp there is this code, which looks obviously wrong:

  if ((m_pObject->getObjectType() == MODELOBJECTTYPE_MODEL) || (MODELOBJECTTYPE_SOLIDSUPPORT)) {

The value of MODELOBJECTTYPE_SOLIDSUPPORT, so this conditional is always true.
Originally from this Debian bug report by John Mullee:

  https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=985903

**Comment by martinweismann** [comment]
Thank you very much!
