### ISSUE TITLE
Building with MSVC without COM

### ISSUE THREAD

**Issue by dimininio** [3MFConsortium/lib3mf#27]
Could you advice how to use lib3mf library on Windows (build by MSVC14 compiler) without COM functions.

I'd like to use lib3mf without of using Microsoft's functions (like for GCC but using MSVC)

I cannot properly define in project's properties ___GNUC_  macro  (NMR_COM_EMULATION, __GCC_WIN32) because it causes redefinition of macroses with consequent errors.

**Comment by martinweismann** [comment]
This is controlled by the NMR_COM_NATIVE - variable in CMake now.
By setting NMR_COM_NATIVE to false (which is the default) you will use the platform independent implementations of the Readers, Writers and OPC package readers on Windows, too.

Enabling NMR_COM_NATIVE will use the platform specific COM implementation of this functionality, as usual.

Does this answer your question?

**Comment by martinweismann** [comment]
Probably solved and now inactive.
