### ISSUE TITLE
static uses of std::random_device are a bit fragile

### ISSUE THREAD

**Issue by drussel** [3MFConsortium/lib3mf#271]
Since at least on linux it opens a file, and at least when statically linked you then are subject to the whims of program teardown order. Not sure if you can count on the teardown order when in a dynamic library. But who wants another file to have to distribute along with your app :-)

We were getting crashes on teardown intermittently which is why we noticed.

Include/Common/NMR_UUID.h
Source/Common/NMR_UUID.cpp
Source/Model/Classes/NMR_Model.cpp

**Comment by martinweismann** [comment]
@drussel : it took a while, but #312 should fix this issue.
