### ISSUE TITLE
putVertexFloat precision not high enough for large models

### ISSUE THREAD

**Issue by SteveAuroraLabs3d** [3MFConsortium/lib3mf#28]
NMR_ModelWriterNode100_Mesh.cpp Line 256: 
`// Format float with "%.3f" syntax`

On a meter unit model more decimal places (around 6 or 1μm) are needed.

**Comment by shahchintan14** [comment]
In general, 3mf format is double precision. But Lib3mf writes the coordinates in 3mf as single precision which causes loss of accuracy in the output 3mf models.

**Comment by martinweismann** [comment]
Hi all,

there are two problems:

1. string output of the geometry is limited to 3 decimal places:
This has been mostly resolved, see NMR_ModelWriterNode100_Mesh.cpp , Line 349
`// Format float with "%.$ACCf" syntax where $ACC = m_snPosAfterDecPoint`
This number of decimal places can be set on compile time. We should make this configurable at runtime.
Another option to make more of a given `"%.*f"`-formatting is to change the default units of a 3MF-model.

2. The 3MF-core spec actually allows arbitrary precision of all coordinate values via their string representation.
I agree that going up to double precision would improve the situation, probably with a small performance loss compared to arbitrary precision. Need to investigate.

**Comment by shahchintan14** [comment]
Regarding point 1, by making the number of decimal places configurable at run-time, do you mean allowing as many decimal places as required by the floating point number in question?

**Comment by martinweismann** [comment]
I would rather expose the number of decimal points to be outputted to the user of the library, e.g. as 
CModelWriter_3MF::SetFloatPrecision(_In_ DWORD nDecimals);

**Comment by martinweismann** [comment]
(I suspect dynamic calculation of the required number of decimals will degrade write-performance.)

**Comment by shahchintan14** [comment]
It seems that the default value of m_snPosAfterDecPoint is 5, currently. Could it be changed to at least 6 so that, as requested in the original comment by @SteveAuroraLabs3d, for the 3mf files in meters we can have precision of at least 1 micrometer, which is essential.
If the m_snPosAfterDecPoint is updated here in lib3mf-master itself, we don't have to change it at our end every time we pull the lib3MF source when it updates.

**Comment by feliperoos** [comment]
Hi @martinweismann,
you mention configuration of the precision at runtime as a future thing. Is there any expectation around when it is going to be available?

**Comment by martinweismann** [comment]
@feliperoos : it's here, finally: https://github.com/3MFConsortium/lib3mf/pull/169
My fears that this change degrades write performance have been unwarranted.
