### ISSUE TITLE
BEGIN_INTERFACE_MAP and END_INTERFACE_MAP conflict with MFC macros

### ISSUE THREAD

**Issue by mloskot** [3MFConsortium/lib3mf#29]
The `Common/Platform/NMR_COM_Native.h` (included via `NMR_COMInterfaces.h` -> `NMR_COMFactory.h`) defines `BEGIN_INTERFACE_MAP` macro.

The MFC `afxwin.h` defines macro with the same name.

If both headers are included, there is an obvious conflict.

Would it be possible to rename these two macros according to `LIB3MF`-prefixed convention used for all the other macros?

**Comment by martinweismann** [comment]
Please see #51. Native COM functionality is very likely to be removed in the future.

**Comment by mloskot** [comment]
Thanks
