### ISSUE TITLE
installing the application

### ISSUE THREAD

**Issue by IgnacioCollantes** [3MFConsortium/lib3mf#3]
Hello,
I'm new in github and developing code but in my company we are very interested in 3D printing and now I'm investigating about new 3D formats. I would like to use the lib3mf but I don't know much about compiling source code. Could you please explain the steps to make the application run in windows or linux?
Thank you very much in advance.
Best regards,
Ignacio.

**Comment by prushenas** [comment]
On windows, you can go to ...\Project\Lib3MF folder and use the Visual Studio solution Lib3MF.sln to build 3MF library files Lib3MF.* or Lib3MFC.* based on the chosen flavours (COM like interface or C like DLL interface). On Linux, you can go in ...\Project\Lib3MFGCC and use the Makfile to generate lib3MF.so.

**Comment by IgnacioCollantes** [comment]
Hello Parviz, thanks for your quick response. In fact I tried to run makefile in ubuntu 12.04.4, but didn't work.
Regards,

**Comment by prushenas** [comment]
I can not attach any file here!
I can provide you with a Makefile that should work on Ubuntu if you give me your email address. 
Parviz

**Comment by alexanderoster** [comment]
Dear Ignacio,

can you post the error messages?

Best,
 Alexander

**Comment by IgnacioCollantes** [comment]
Hello!
Parviz, my address is ignacio.collantes@atos.net.

and after supressing some blanks in the Makefile file, the first errors are
Makefile_v1: 21: Makefile_v1: -I../../Include: not found
Makefile_v1: 22: Makefile_v1: -std=c++11: not found
Makefile_v1: 23: Makefile_v1: -Wall: not found
Makefile_v1: 33: Makefile_v1: -I../../Include: not found
Makefile_v1: 34: Makefile_v1: -O2: not found
Makefile_v1: 35: Makefile_v1: -O2: not found
Makefile_v1: 40: Makefile_v1: -s: not found
Makefile_v1: 44: Makefile_v1: clean_release:: not found
Makefile_v1: 45: Makefile_v1: OBJ_RELEASE: not found
Makefile_v1: 45: Makefile_v1: OUT_RELEASE: not found
Makefile_v1: 47: Makefile_v1: OBJDIR_RELEASE: not found

I have a low knowledge of linux. Maybe these error are basics...
Thank you very much.
Best regards,
Ignacio.

**Comment by prushenas** [comment]
Hi Ignacio
Attached the updated Makefile for Linux.
Let us know if any issues.
Thanks
Parviz

**Comment by IgnacioCollantes** [comment]
sorry Parviz, I can't see the attached file... :)

**Comment by prushenas** [comment]
It was attached to the email!
I re-send it again directly to you.
Parviz

**Comment by sharayumane** [comment]
hi all,

I want to install the same on windows 7 
i am not able to build the project from VS2012
it giving syntactical errors on all the lines where "CModelWriterNode() = delete;" such kind of syntax is used.
i am new to 3MF.

Please help me ASAP.

Thank you. :)

**Comment by mloskot** [comment]
@sharayumane The .sln and .vcxproj files in `Project/Lib3MF` folder have been created with Visual Studio 2013, so it is safe to assume, you need VS2013 or later to build the library.

FYI, `CModelWriterNode() = delete;` is [correct C++11 syntax](http://en.cppreference.com/w/cpp/language/function#Deleted_functions), but you need Visual C++ from VS2013 or later.

**Comment by sharayumane** [comment]
I tried in VS 2015 
still giving same error
Will you please tell now what's the issue?

**Comment by mloskot** [comment]
@sharayumane  I have **successfully** built the current master branch of lib3mf with VS2013 Update 4 and VS2015 Update 2. I suggest you to double check that you are building with one of those IDEs using the provided `Lib3MF.sln`.

**Comment by martinweismann** [comment]
If this still happens with the latest version and CMake, please raise another issue.
