### ISSUE TITLE
CMakeLists.txt missing target to build lib3MF with COM interface

### ISSUE THREAD

**Issue by mloskot** [3MFConsortium/lib3mf#30]
Initially, on Windows, it was possible to use `Project\Lib3MF\Lib3MF.sln` to build 3MF library targets `Lib3MF.{dll|lib}` or `Lib3MFC..{dll|lib}`, that is either library with COM-like interface or C-like DLL interface.

In https://github.com/3MFConsortium/lib3mf/commit/7e252f35da8b059b3e30144657ea25a997b8fd34 the project switched from to CMake as build configuration.

The CMake configuration defines only one target that builds `lib3MF.{dll|lib|`, that apparently is the second flavour of the library, with C-like interface.

There is no target to build the library with COM-like interface.
 
Is that intentional?

**Comment by martinweismann** [comment]
We do not want to loose the COM-interface / build target. We just haven't looked into this for a while even before the switch to CMake (I am not sure it worked before).
It would be highly appreciated if you, or anyone else with enough knowledge on this topic, could contribute to the CMake-setup for the COM-interface!

**Comment by mloskot** [comment]
@martinweismann Thanks for the CMake configuration update in #27
