### ISSUE TITLE
Update googletest or increase C++ standard?

### ISSUE THREAD

**Issue by waebbl** [3MFConsortium/lib3mf#308]
The current googletest submodule refers to gtest-1.8.1 back from 2019. Newer versions (current 1.13.0) need C++14, while the library uses C++11 for GNU compilers and on Darwin, which leads to build failures for some of the unit tests[1]

Are there any objections on either updating the googletest submodule and the unit tests or dropping the C++11 requirement? A local test shows[2], that it seems to build at least on linux systems if C++11 is dropped from the `CMakeLists.txt` file.

[1] https://bugs.gentoo.org/895180
[2] https://github.com/gentoo/gentoo/pull/29644

**Comment by alexanderoster** [comment]
Hi Bernd,

Thank you so much for reaching out. We do not have reservations and will upgrade the submodule accordingly.

Best,

Alex

**Comment by martinweismann** [comment]
Hi @waebbl ,
please give the develop branch a try now. Since #311 , you should be fine now.
Cheers!

**Comment by waebbl** [comment]
Hi @martinweismann,
thank you very much for updating. On my test, the build and tests now work with the current googletest.
Best,
Bernd
