### ISSUE TITLE
Python wheels for Python bindings

### ISSUE THREAD

**Issue by vijaiaeroastro** [3MFConsortium/lib3mf#350]
All Python bindings (Windows, Linux and OSX) should be distributed as Python wheels and made available through PIP for easier adoption of lib3mf.

**Comment by martinweismann** [comment]
Thanks @vijaiaeroastro 

This works for me (Windows 11, python 3.11.8).

Can we call the library lib3mf in most places? After to many inconsistencies we decided to call the library lib3mf (over lib3MF, Lib3mf, Lib3MF) as often as possible (namespaces in C++ are still Lib3MF, though).
![image](https://github.com/3MFConsortium/lib3mf/assets/30837766/fd00a0a1-87a4-4b90-aa6c-ad9805396184)

What are the next steps to releasing this on Pip with every lib3mf release?

I held off posting to https://github.com/Ghostkeeper/Blender3mfFormat
Let’s have more interesting Python examples in place before posting there. They will want those examples anyway.

Thanks!
