### ISSUE TITLE
Adding Customized Data folder/file inside 3MF

### ISSUE THREAD

**Issue by amitgpatil** [3MFConsortium/lib3mf#37]
Hi,

I want to embed customized folder with data file inside folder "3D" of 3MF file. This data is extra metadata having printer specific information.
Please let me know how to achieve this using LIB3MF Library.

Regards,
Amit

**Comment by martinweismann** [comment]
Hi @amitgpatil 

please have a look at the code of the test that covers attachments
https://github.com/3MFConsortium/lib3mf/blob/master/Source/UnitTests/UnitTest_Attachments.cpp#L66

In this test, the "Attachments" folder is created as sibling of the "3D"-folder ("/Attachments/test.xml"). To make it a child of the "3D" folder, change the path to "/3D/Attachments/test.xml" when calling lib3mf_model_addattachmentutf8.

Is that what you are looking for?
