### ISSUE TITLE
Lib3MF cannot handle multiproperties (Default property on triangle being required)

### ISSUE THREAD

**Issue by feliperoos** [3MFConsortium/lib3mf#38]
Hello,

I'm looking through some issues found regarding default properties on triangles. They seem to be required, while the spec says they're not:
> If p1 is not specified then the default object property, **if specified,** is assigned to the triangle.  If p2 or p3 is unspecified then p1 is used for the entire triangle.

I've the following case. The model goes like this:
```
<m:colorgroup id="6">
  <m:color color="#FFFFFF"/>
  [...]
<m:texture2d contenttype="image/png" id="4" path="/3D/textures/photo_3.png"/>
<m:texture2dgroup id="9" texid="4">
  <m:tex2coord u="1" v="1"/>
  [...]
<m:multiproperties id="10" pids="6 9">
  <m:multi pindices="3 0"/>
  <m:multi pindices="3 1"/>
  <m:multi pindices="3 2"/>
  <m:multi pindices="3 3"/>
</m:multiproperties>
<object id="1" p:UUID="cb828680-8895-4e08-a1fc-bb63e034df16" pid="10" pindex="0" type="model">
  <mesh>
    <vertices>
      [...]
    <triangles>
      <triangle p1="0" p2="1" p3="2" pid="6" v1="0" v2="1" v3="2"/>
      <triangle v1="2" v2="4" v3="0"/>
      [...]
[...]
<build p:UUID="cb828680-8895-4e08-a1fc-bb63e034cf16">
  <item objectid="1" p:UUID="cb828680-8895-4e08-a1fc-bb62e034df16" transform="1.0000 0.0000 0.0000 0.0000 1.0000 0.0000 0.0000 0.0000 1.0000 30.1000 35.1000 5.1000"/>
</build>
```
This is currently failing on (what I can only assume to be) the check at Source/Model/Writer/v100/NMR_ModelWriterNode100_Mesh.cpp@164
```
// if there is a PID, but no DefaultProperty
if ( (pBaseMaterials) || (pNodeColors) || (pTexCoords) ) {
	if ( !(m_pModelMeshObject->getDefaultProperty()) ) {
		throw CNMRException(NMR_ERROR_MISSINGDEFAULTPID);
	}
}
```
I would like to understand why the object doesn't have a default property given that it does have a pid set, and why would it be required for the triangle since the spec doesn't require it.

**Comment by martinweismann** [comment]
Hi @feliperoos 

your xml-snippet looks completely fine, and your assessment of the specification is correct.

The problem is that lib3MF cannot read (or write) multiproperties or composite materials.
In your example, lib3MF ignores the resource with id=10 of type multiproperties and acts as if id=10 was not set. Triangle 2 falls back to the default property of the mesh which cannot be found.

I changed the title of the Issue to describe the root cause for this behaviour and added a pull request to at least issue a warning when multiproprties are encountered.

**Comment by feliperoos** [comment]
This is very much appreciated, @martinweismann. Thanks for your support.

**Comment by qmuntal** [comment]
@martinweismann Do you know if this limitation is and inherent problem of how is architectured the library or it is just not implemented yet cause time constraints?

**Comment by martinweismann** [comment]
@qmuntal :
There is no fundamental limitation in lib3MF that would hinder implementing multiproperties. We just did not have time to do that, yet.

Having said that, lib3mf currently implements all properties via a `CMeshInformation` in the `CMeshInformationHandler` (https://github.com/3MFConsortium/lib3mf/blob/master/Include/Common/MeshInformation/NMR_MeshInformationHandler.h#L43).
This approach is convenient for individual types of properties (color or texture) as it allows manipulating them on the level of their logical meaning (RGB values and UV coordinates per triangle node).
Preparing the actual XML entities (`pid`+`pindex` from `<colorgroup>`+`<color>` or `<texture2d>`+`<tex2coord>`) is done by writer and reader, respectively. This logic can easily be done for these simple types of properties.

Something similar will be cumbersome but certainly possible for for multiproperties.

It is very likely, though, that the `CMeshInformationHandler`  which holds `std::vector<PMeshInformation> m_pInformations;` is _not the right approach_ for multiproperties and instead a datamodel more similar to the specification itself should be implemented: https://github.com/3MFConsortium/spec_materials/blob/master/3MF%20Materials%20Extension.md#chapter-5-multiproperties 

I am happy to discuss this in detail in case you have ideas about multiproperties for lib3mf!

**Comment by qmuntal** [comment]
@martinweismann Thaniks for the detailed answer. At the moment it is not in my top priorities to use multiproperties, but when it happens we can have the discussion.

**Comment by shahchintan14** [comment]
@martinweismann Any update on this? Any plans or ongoing work to implement multiproperties in lib3mf?

**Comment by martinweismann** [comment]
Hi @shahchintan14 ,
yes (finally)! We are right now implementing multiproperties as part of the next major version of lib3mf. This major update will close a number of gaps between the implementation and the core- and extension- specifications and will make the usage of lib3mf's API much more convenient.
ETA: mid of march.

**Comment by martinweismann** [comment]
@qmuntal @feliperoos @shahchintan14 : Version 2 of lib3mf will support this!
Please try this in the [alpha-release of version 2.0](https://github.com/3MFConsortium/lib3mf/releases/tag/v2.0.0-alpha).

**Comment by martinweismann** [comment]
Hi @qmuntal @feliperoos @shahchintan14, [v2.0.0-beta](https://github.com/3MFConsortium/lib3mf/releases/tag/v2.0.0-beta). has further improved the support for multiproperties. This should resolve this issue.
