### ISSUE TITLE
examples for texture and color?

### ISSUE THREAD

**Issue by markm72homeruns** [3MFConsortium/lib3mf#4]
None of the examples show how to add texture or color. Can you add one for that as well. Is this part of the library ready?

**Comment by netfabb** [comment]
Hi Mark,

yes, it is part of the library. We will create an example for this and update github to a new Revision next week!

Best regards,
Alex

> Am 06.11.2015 um 22:13 schrieb markm72homeruns <notifications@github.com>:
> 
> None of the examples show how to add texture or color. Can you add one for that as well. Is this part of the library ready?
> 
> —
> Reply to this email directly or view it on GitHub.
> 

--
Best regards

Dipl.-Math. Alexander Oster
CEO
_______________________________________________

Materialica * 20.-22. Oktober 2015  * München
DKOU        * 20.-23. Oktober 2015  * Berlin
AIRTEC      * 03.-05. November 2015 * München
formnext    * 17.-20. November 2015 * Frankfurt
_______________________________________________

netfabb GmbH
Eichenbühl 10
92331 Lupburg
Germany

Phone:  +49 94 92 60 16 40 0
Fax:    +49 94 92 60 16 40 9
Mail:   alexander.oster@netfabb.com
Web:    www.netfabb.com
Skype:  alexander.oster

CEO: Dipl.-Math. Alexander Oster
Court of jurisdiction: Amtsgericht Nuremberg HRB 25345
VAT-No.: DE264795045

You can always contact us at: info@netfabb.com
