### ISSUE TITLE
Link error on Mac OS X 10.11.2

### ISSUE THREAD

**Issue by sny1985** [3MFConsortium/lib3mf#5]
I just ran the makefile on my Mac.

ld: warning: option -s is obsolete and being ignored
ld: internal error: atom not found in symbolIndex(__ZNSt3__16vectorINS_10shared_ptrIN3NMR15CModelBuildItemEEENS_9allocatorIS4_EEE21__push_back_slow_pathIRKS4_EEvOT_) for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: **\* [out_release] Error 1

Anyone knows how to solve it?

**Comment by martinweismann** [comment]
This should be fixed with the new CMake build system.
