### ISSUE TITLE
Build using NMR_COM_NATIVE TRUE fails

### ISSUE THREAD

**Issue by meljaeger** [3MFConsortium/lib3mf#51]
Hi,

Building with NMR_COM_NATIVE set to TRUE fails with the following errors:

```
1>------ Build started: Project: lib3MF, Configuration: Release x64 ------
1>  NMR_ModelReader_3MF_OPC.cpp
1>C:\Dev\lib3mf\Source\Model\Reader\NMR_ModelReader_3MF_OPC.cpp(411): error C3861: 'addTextureStream': identifier not found
1>  NMR_COMInterface_ModelTexture2D.cpp
1>C:\Dev\lib3mf\Source\Model\COM\NMR_COMInterface_ModelTexture2D.cpp(804): error C2039: 'removeTextureStream': is not a member of 'NMR::CModel'
1>  C:\Dev\lib3mf\Include\Model/Classes/NMR_ModelTexture2D.h(49): note: see declaration of 'NMR::CModel'
1>C:\Dev\lib3mf\Source\Model\COM\NMR_COMInterface_ModelTexture2D.cpp(805): error C2039: 'addTextureStream': is not a member of 'NMR::CModel'
1>  C:\Dev\lib3mf\Include\Model/Classes/NMR_ModelTexture2D.h(49): note: see declaration of 'NMR::CModel'
1>  Generating Code...
========== Build: 0 succeeded, 1 failed, 1 up-to-date, 0 skipped ==========
```
If property is set to FALSE, all works well. I need an updated version of the library with the same COM interfaces for compatibility.

**Comment by martinweismann** [comment]
**Current situation:**
The COM-interface of Lib3MF has been barely maintained over the last years and I am not sure whether the -DNMR_COM_NATIVE=ON setting currently produces valid COM classes.
The reason for these points is that the active contributors and maintainers of the project do not actively use the COM interface.

**The path forward:**
Considering that we want to keep lib3MF as platform independent as possible, we will most likely remove the COM interface.
The actual C++-classes will stay (e.g. CCOMInterface_ModelMeshObject, or CCOMModelBuildItem), however, they will loose their connection to COM (e.g. "CCOMModelBuildItem" might essentially become a "CModelBuildItem"). 
We will advocate using either these classes as regular C++-classes or using the language neutral C-interface that simply wraps those classes.

Regarding COM: If users want, they can write a COM wrapper around the (soon to be plain) C++-classes.
