### ISSUE TITLE
MXE/MinGW builds currently fail

### ISSUE THREAD

**Issue by martinweismann** [3MFConsortium/lib3mf#57]
From https://github.com/3MFConsortium/lib3mf/pull/44 :

It [The configuration] picks the wrong path for MXE/MinGW builds with if (UNIX). Changing that to if (UNIX OR MINGW) should solve that. Or maybe switching the conditions and use WIN32?

**Comment by martinweismann** [comment]
@t-paul : Could you give this a try?

**Comment by t-paul** [comment]
#64 enables GCC flags for MinGW. I can't fully test the MXE build yet as the new library dependency (libuuid) is not in MXE. I hope this is easy to add aswell...
