### ISSUE TITLE
"Real" COM Version of lib3mf

### ISSUE THREAD

**Issue by odalet** [3MFConsortium/lib3mf#6]
I'd wish to call into lib3mf from C# code; the only way I'm seing right now is to interop against the C API version by hand. It'd be far quicker if I could just let Visual Studio generate a wrapper for me from the COM version. 

Hence, would it be possible to have lib3mf compile to a **true** COM component; i.e. something I can run regsvr32 against?

I'm not enough c++ aware to implement this by myself: I really don't know what I should put in `DllRegisterServer`...

Thanks

**Comment by martinweismann** [comment]
Hi @odalet ,

lib3MF is intended to and used to have a true COM interface in earlier versions. However, this was not maintained properly and does not work correctly right now.
I am closing this issue because it is covered under 
https://github.com/3MFConsortium/lib3mf/issues/30 

Thanks

**Comment by odalet** [comment]
Thanks for proving with your reply that the project is not dead! 

Btw, I managed, in the meantime, to build my own fully managed 3MF reader by simply using Microsoft's OPC assemblies...
Nevertheless, a COM version of the reader might still be of some interest to me

Thanks,
