### ISSUE TITLE
Some sample files not readable with GCC library (error #1035: Could not read ZIP file)

### ISSUE THREAD

**Issue by t-paul** [3MFConsortium/lib3mf#7]
Using the GCC library version on Debian, it's not possible to read a number of sample files provided in the `3mf-samples` repo. All fail with the same error message when running the `Converter` example program:
```
could not parse file: 80004005
error #1035: Could not read ZIP file
```
List of files that fail:
* lib3mf-samples.git/geometries/torus.3mf...
* lib3mf-samples.git/materials/kinect_scan.3mf...
* lib3mf-samples.git/materials/multipletextures.3mf...
* lib3mf-samples.git/materials/pyramid_vertexcolor.3mf...
* lib3mf-samples.git/materials/rhombicuboctahedron_color.3mf...
* lib3mf-samples.git/materials/sphere_logo.3mf...

Many thanks for adding gcc support, that is extremely useful.

**Comment by t-paul** [comment]
Digging a bit deeper, the reason for the failure seems to be that `libzip` detects the ZIP files to be multi-disk archives which are not supported.

This is due to the "end of central directory" being set to all 0xff.
```
$ hd -s 0x5297 torus.3mf 
00005297  50 4b 05 06 ff ff ff ff  ff ff ff ff ff ff ff ff  |PK..............|
000052a7  ff ff ff ff 00 00                                 |......|
```

**Comment by phaazon** [comment]
I second this. Is there anything planned to fix this? I can help.

**Comment by phaazon** [comment]
I just had a look and it looks like the incriminated code is the following:

```
m_ZIParchive = zip_open_from_source(m_ZIPsource, ZIP_RDONLY | ZIP_CHECKCONS, &m_ZIPError);
if (m_ZIParchive == nullptr) {
  // error generated here
```

I’m trying to figure out what’s going on.

**Comment by t-paul** [comment]
It fails due to: https://github.com/3MFConsortium/lib3mf/blob/master/Source/Libraries/libzip/zip_open.c#L280 triggering the multi-zip error (ZIP_ER_MULTIDISK). This line reads the first 4 bytes of the "end of central directory", directly after the PK\5\6 marker and expects both to be 0 (which means single-disk-archive).

The two entries are (according to https://users.cs.jmu.edu/buchhofp/forensics/formats/pkzip.html)
```
Disk Number 	The number of this disk (containing the end of central directory record)
Disk # w/cd 	Number of the disk on which the central directory starts 
```

I'm not sure if it's a problem with libzip (maybe not detecting a zip64 format?) or if it's just the files having an invalid "end of central directory".

**Comment by phaazon** [comment]
I tested with several .3mf files (even those created from Windows 10), and it always fails, so the problem is due to the lib, not the files.

Thank you for the explanation. I still have no idea how to fix that quickly.

**Comment by t-paul** [comment]
Created how? Using lib3mf compiled with GCC on Windows? I'm pretty sure the native Windows implementation does not use libzip but likely the Windows OPC code (but I did not check the code for that yet).

The 3mf files I'm generating using lib3mf/libzip/GCC on Linux are perfectly ok and have a sensible "end of central directory".

**Comment by phaazon** [comment]
No you misread me. The .3mf files are created with another tool (3D Builter, the built-in Windows application).

**Comment by phaazon** [comment]
Any idea on how to rezip a .3mf? Like, calling `unzip` then `zip` on the extracted files? That would be useful as temporary fix for my use case and I could work on the issue more relieved.

**Comment by prushenas** [comment]
You could go in the folder that you have 3MF related documents (i.e. 3D, _refls,...) and then select all and then right click and use 7-zip (7zFM.exe) to create a .zip file by adding the selected files. Then rename the new compressed zipped file by changing its extension from zip to 3mf.

**Comment by prushenas** [comment]
Note that on Windows, you could  select the files and then right click and select  "Send to" "Compresseed (zipped) folder" to generate the file.

**Comment by phaazon** [comment]
I’m on linux. The idea is to unzip files written on Windows then zip them back on linux. But when I do this I get error on the signature of the 3mf file.

**Comment by t-paul** [comment]
It's probably fine to just use any other ZIP tool, even on Windows. It seems it's 3D-Builder which creates the files that can't be read by libzip. I've pinged the libzip mailing list, maybe someone there can add some information.

On Linux just re-zipping with `zip` looks fine, at least the `Converter` example can read the file afterwards (and the generated STL looks ok in a 3d viewer).
```
$ ls -la
total 96
drwxr-xr-x  2 tp   users  4096 Feb 13 17:26 .
drwxrwxrwt 21 root root  65536 Feb 13 17:26 ..
-rw-r--r--  1 tp   users 21165 Feb 13 17:24 torus.3mf
$ Converter torus.3mf 
------------------------------------------------------------------
3MF Model Converter
------------------------------------------------------------------
reading torus.3mf...
could not parse file: 80004005
error #1035: Could not read ZIP file
$ mkdir t
$ cd t
$ unzip ../torus.3mf 
Archive:  ../torus.3mf
  inflating: _rels/.rels             
  inflating: 3D/3dmodel.model        
  inflating: [Content_Types].xml     
$ zip -9r ../torus2.3mf _rels 3D '[Content_Types].xml'
  adding: _rels/ (stored 0%)
  adding: _rels/.rels (deflated 32%)
  adding: 3D/ (stored 0%)
  adding: 3D/3dmodel.model (deflated 89%)
  adding: [Content_Types].xml (deflated 39%)
$ cd ..
$ ls -la
total 124
drwxr-xr-x  3 tp   users  4096 Feb 13 17:27 .
drwxrwxrwt 21 root root  65536 Feb 13 17:26 ..
drwxr-xr-x  4 tp   users  4096 Feb 13 17:27 t
-rw-r--r--  1 tp   users 21363 Feb 13 17:27 torus2.3mf
-rw-r--r--  1 tp   users 21165 Feb 13 17:24 torus.3mf
$ Converter torus2.3mf 
------------------------------------------------------------------
3MF Model Converter
------------------------------------------------------------------
reading torus2.3mf...
elapsed time: 0ms
writing torus2.stl...
elapsed time: 0ms
done
$ ls -la
total 232
drwxr-xr-x  3 tp   users   4096 Feb 13 17:27 .
drwxrwxrwt 21 root root   65536 Feb 13 17:26 ..
drwxr-xr-x  4 tp   users   4096 Feb 13 17:27 t
-rw-r--r--  1 tp   users  21363 Feb 13 17:27 torus2.3mf
-rw-r--r--  1 tp   users 110084 Feb 13 17:27 torus2.stl
-rw-r--r--  1 tp   users  21165 Feb 13 17:24 torus.3mf
```

**Comment by phaazon** [comment]
Cool! I’ll try that on Monday! Thanks!

**Comment by t-paul** [comment]
I just got a patch for `libzip` on the mailing list, so hold on with re-zipping the files... testing now...

**Comment by t-paul** [comment]
With the patch, I can open all the sample file without any problems. (Patch on the `libzip` mailing list: http://www.nih.at/listarchive/libzip-discuss/msg00655.html).

Please let me know how to proceed. If wanted, I can create a pull request with that patch. As alternative, the author of the patch offered to create a library patch release.

**Comment by phaazon** [comment]
I guess a library patch release would be appreciated. I’ll apply the patch as well to test! Thanks!

**Comment by 0-wiz-0** [comment]
I've just released libzip-1.1.2 which includes the fix.

Btw, now there is also a github mirror of the libzip repository available at http://github.com/nih-at/libzip

**Comment by phaazon** [comment]
Thanks, awesome! :)

**Comment by prushenas** [comment]
With the patch, I can only import geometries/torus.3mf file and not the 3mf files from materials folder! 
Does anybody else have similar issue?

**Comment by phaazon** [comment]
May you post the error messages? Because I can load them.

**Comment by prushenas** [comment]
Same previous error message: returned error is 80004005

**Comment by 0-wiz-0** [comment]
Can you please make sure your sources are synced up completely with libzip-1.1.2?

**Comment by prushenas** [comment]
Once synced, 3MF files are imported successfully.
