### ISSUE TITLE
possible ZIP64 issue

### ISSUE THREAD

**Issue by pencerw** [3MFConsortium/lib3mf#81]

**Comment by martinweismann** [comment]
@KurtRenap, @alexanderoster, @ALL, do you have any other issues with ZIP64 in lib3MF?
( Except for what is solved with: https://github.com/3MFConsortium/lib3mf/pull/85 )

**Comment by martinweismann** [comment]
TODO: link ZIP_CHECKCONS results to warning / error in strictmode, if this is not a performance issue.
Otherwise, add a distinct property to the reader
