### ISSUE TITLE
How to build 3MF?

### ISSUE THREAD

**Issue by bmarjuna** [3MFConsortium/lib3mf#97]
I'm new to Git dev environment. I need your help in building lib3MF on Windows 7 64-bit machine. I downloaded lib3mf-master.zip from github and extracted it into a new directory (also installed cmake).

As per the build instructions "README.md", i need to run `git submodule update --init` command. Should i run it from cmd? Once this is done, should I need to run 'cmake/GenerateVS2015.bat' from cmd?

**Comment by martinweismann** [comment]
Hi @bmarjuna,
I updated the description of lib3MF with a section "Using lib3mf". Does this help you?
https://github.com/3MFConsortium/lib3mf/tree/Description

**Comment by bmarjuna** [comment]
This is very helpful. I'm able to build the targets. Thanks.
